# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bf016820c4f760909c554d15b0ab556725944f2325244043c15e50144c515240cfdaabde5d0ecd00ef25127d4f63c7007e56519307196e8394b60297e6f3d42

test:
  secret_key_base: ab94668a510a0f26a1186f90bae6fc8cce45420b1f0d7d25f1331bf11c67360536b1a6d23aa86e80471af7b3dd27028c8a3b54752f74065bc963dc209f55b76a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
